### ISSUE TITLE
과제 06의 문제정의

### ISSUE THREAD

**Issue by devcyjung** [devDingco/codecamp-questionTable#3]
# 💻 Default Information

### 📝 Check List
문제 해결을 위해 수행한 단계의 대괄호 안에 x를 입력하여 체크해 주세요.
- [ v] Question Table Issue 검색을 해보았다.
- [v ] Issue와 해결방안에 대해서 곰곰이 생각을 해보았다.
- [ v] 문제해결을 위해 Google, Stackoverflow 등에서 검색을 해보았다.

### 🖥️ Basic Information
정확한 답변을 위해 여러분의 개발 환경과 이슈가 발생한 기술에 대해 알려주세요.
- OS:
- Node version:
- Stack:

# 🙋‍♀️ Issue

### Issue
📣 Issue를 남겨주세요.
📣 사진 첨부가 필요한 경우, 에디터 하단의 'Paste, drop, or click to add files'을 클릭하세요.
📣 코드 첨부가 필요한 경우, 전체 코드 상단과 하단에 백틱(`)을 3번 입력하여 감싸주세요.

### keywords
Issue 해결을 위해 시도한 방법들을 알려주세요.
>

과제 06 설명중에 이해가 안가는 문구가 있는데 정확하게 정의해주시면 감사하겠습니다
1. 필터의 배경색이 반전됨
2. 플로팅 버튼

**Comment by devDingco** [comment]
질문해주신 부분에 대해 추가 설명을 [해당 노션 페이지](https://www.notion.so/dingco/Day-06-454055ee9fa74e54a96a2cc671efc6cf?pvs=4)에 작성해두었으니 확인해주시면 감사하겠습니다.
